Factories = {
    "armlab",
    "armalab",
    "armvp",
    "armavp",
    "armap",
    "armaap",
    "armshltx",
    "armsy",
    "armasy",
    "armshltxuw",
    --
    "corlab",
    "coralab",
    "corap",
    "coraap",
    "corvp",
    "coravp",
    "corgant",
    "corsy",
    "corasy",
    "corgantuw",
}

FactoriesExcludedUnits = {
    "armatlas",
    "armdfly",
    -- "armmlv",
    -- "armbeaver",
    "armtship",
    -- "armthovr",
    --"armscab",
    -- "corape",
    -- "corvalk",
    "corseah",
    -- "cormuskrat",
    -- "corintr",
    "cortship",
    -- "corthovr",
    -- "cormabm",
}
