---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MaDDo.
--- DateTime: 31-Jul-19 4:55 PM
---
function gadget:GetInfo()
    return {
        name 	= "Cmd - Gfx Buttons",
        desc	= "Adds button images on top of command buttons",
        author	= "MaDDoX",
        date	= "Feb 14 2020",
        license	= "GNU GPL, v2 or later",
        layer	= 10,
        enabled = true, --true, (WIP)
    }
end

VFS.Include("gamedata/taptools.lua")
--VFS.Include("luarules/configs/global_upgradedata.lua")

--local spGetUnitDefID        = Spring.GetUnitDefID
--local spGetUnitCmdDescs     = Spring.GetUnitCmdDescs
local spGetUnitTeam         = Spring.GetUnitTeam
local spSetUnitRulesParam   = Spring.SetUnitRulesParam
local spGetGameFrame        = Spring.GetGameFrame
local spUseUnitResource     = Spring.UseUnitResource
local spGetUnitHealth       = Spring.GetUnitHealth

local spGetUnitCmdDescs = Spring.GetUnitCmdDescs
local spFindUnitCmdDesc = Spring.FindUnitCmdDesc
local spEditUnitCmdDesc = Spring.EditUnitCmdDesc
local CMD_ATTACK = CMD.ATTACK

if not gadgetHandler:IsSyncedCode() then
    return end

GfxButtons = {
    -- key = upgrade id
    CMD_ATTACK = {
        --id      = CMD_ATTACK,
        --name    = 'ATTACK',
        --action  = 'upgradecapture',
        --cursor  = 'Morph',
        --type    = CMDTYPE.ICON,
        --tooltip = 'Unlocks the Capture ability of all builder units',
        texture = 'luaui/images/gfxbuttons/cmd_attack.dds',
        onlyTexture = true,
        --showUnique = true, --required by gui_chili_buildordermenu to show button as 'upgrading'
    }
}

--Spring.GetUnitCmdDescs ( number unitID [, number startIndex [, number endIndex ] ] ) -> nil | {
    --[1] = {
        --"id"          = number,
        --"type"        = number,
        --"name"        = string,
        --"action"      = string,
        --"tooltip"     = string,
        --"texture"     = string,
        --"cursor"      = string,
        --"hidden"      = boolean,
        --"disabled"    = boolean,
        --"showUnique"  = boolean,
        --"onlyTexture" = boolean,
        --"params"      = { [1] = string, ... }
    --}, ...
--}

function gadget:UnitCreated(unitID, unitDefID, unitTeam)
    local cmdId = spFindUnitCmdDesc(unitID, CMD_ATTACK)
    if not cmdId then
        return end
    local cmdDesc = spGetUnitCmdDescs(unitID, cmdId, cmdId)[1]
    if not cmdDesc then
        Spring.Echo("Cmd Descs finding failed")
    else
        Spring.Echo("Cmd Descs found")
    end
    cmdDesc.texture = 'luaui/images/gfxbuttons/cmd_attack.dds' --GfxButtons.CMD_ATTACK.texture
    cmdDesc.onlyTexture = true --GfxButtons.CMD_ATTACK.onlyTexture
    AddUpdateCommand(unitID, cmdDesc)
    --spEditUnitCmdDesc(unitID, cmdIdx, cmdDesc)

    --for cmdID, cmdDesc in pairs(GfxButtons) do
    --    if GfxButtons[thisCmdID] then
    --        local cmdDesc = upgData.UpgradeCmdDesc
    --        if cmdDesc then
    --            upgData.buttonToUnlockTooltip = cmdDesc.tooltip end
    --        AddUpdateCommand(unitID, cmdDesc)
    --    end
    --end
end

function gadget:Initialize()
    --TODO: For all existing units, call unitcreated
end

-- If unit was taken, apply unit-creation check
function gadget:UnitTaken(unitID, unitDefID, oldTeamID, teamID)
    self:UnitCreated(unitID, unitDefID, teamID)
    --if isDone(unitID) then self:UnitFinished(unitID, unitDefID, teamID) end
end