---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Breno.
--- DateTime: 22-Jul-20 10:13 PM
---
---
--- Created by Breno "MaDDoX" Azevedo.
---
if not gadgetHandler:IsSyncedCode() then
    return end

-----------------
---- SYNCED
-----------------
--VFS.Include("gamedata/taptools.lua")

function gadget:GetInfo()
    return {
        name      = "Neutral Walls",
        desc      = "Makes any spawned dragon teeth or fort wall become neutral, so it isn't auto-targeted",
        author    = "MaDDoX",
        date      = "22 July 2020",
        license   = "GNU GPL, v2 or later",
        layer     = 0,
        enabled   = true,
    }
end

local spSetUnitNeutral = Spring.SetUnitNeutral

local wallDefIDs = {
    [UnitDefNames["armdrag"].id] = true,
    [UnitDefNames["cordrag"].id] = true,
    [UnitDefNames["armfort"].id] = true,
    [UnitDefNames["corfort"].id] = true,
}

local function isWall(unitDefID)
    return wallDefIDs[unitDefID]
end

function gadget:UnitFinished(unitID, unitDefID, teamID)
    if isWall(unitDefID) then
        spSetUnitNeutral(unitID, true)
    end
end

