return {
	corvrad = {
		acceleration = 0.03,
		activatewhenbuilt = true,
		brakerate = 0.036,
		buildcostenergy = 1300,
		buildcostmetal = 90,
		buildpic = "CORVRAD.DDS",
		buildtime = 4223,
		canattack = false,
		canmove = true,
		category = "ALL TANK MOBILE NOTSUB NOWEAPON NOTSHIP NOTAIR SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "24 18 29",
		collisionvolumetype = "box",
		corpse = "dead",
		description = "Radar Vehicle",
		energymake = 8,
		energyuse = 20,
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxdamage = 510,
		maxslope = 16,
		maxvelocity = 1.09,
		maxwaterdepth = 0,
		movementclass = "TANK3",
		name = "Informer",
		objectname = "CORVRAD",
		onoffable = true,
		radardistance = 2200,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 900,
		sonardistance = 0,
		trackstrength = 10,
		tracktype = "StdTank",
		trackwidth = 23,
		turninplace = true,
		turninplaceanglelimit = 110,
		turninplacespeedlimit = 0.825,
		turnrate = 210,
		customparams = {
			bar_trackstrength = 10,
			bar_tracktype = "corwidetracks",
			bar_trackwidth = 23,
			techlevel = 2,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.611381530762 -0.0270607836914 -0.43489074707",
				collisionvolumescales = "23.1105194092 8.20951843262 32.5806274414",
				collisionvolumetype = "Box",
				damage = 546,
				description = "Informer Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 64,
				object = "CORVRAD_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 450,
				description = "Informer Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 48,
				object = "2X2F",
                collisionvolumescales = "35.0 4.0 6.0",
                collisionvolumetype = "cylY",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = { 
 			pieceExplosionGenerators = { 
				"deathceg2",
				"deathceg3",
				"deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "cvradsel",
			},
		},
        weapondefs = {
            meteor_painter={
                craterboost=0,
                rgbcolor="0.8 0 1",
                gravityaffected="false",
                firestarter=0,
                areaofeffect=0,
                explosiongenerator="custom:meteorstrike-tag",
                predictboost=0.5,
                avoidfeature=false,
                proximitypriority=-10,
                craterareaofeffect=70,
                impactonly=1,
                impulsefactor=0,
                soundhitwetvolume=0.5,
                soundhit="xplosml3",
                soundstart="canlite3",
                weapontype="BeamLaser",
                name="meteorstriketagger",
                noselfdamage=true,
                soundhitwet="sizzle",
                impulseboost=0,
                cratermult=0,
                weaponvelocity=800,
                turret=true,
                targetmoveerror=0.05,
                laserflaresize=12,
                accuracy=120,
                corethickness=0.22499999,
                beamtime=0.5,
                damage={
                    default=1,
                },
                reloadtime=20,
                range=400,
            },
        },
        weapons = {
            [1] = {
                name="corvrad_meteor_painter",
                onlytargetcategory="SURFACE",
            },
        },
    },
}
